version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: fix
      prefix-development: chore
  - package-ecosystem: npm
    directory: "/example"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
